// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'5fc231ed896102f9f6cb666d5a2ac25bf18b534209158a9bec904406222d1b29'>;
export type ExecutionHash =
  ExecutionHashBase<'6b5268b252dc6310e25303ec736c644e28b44af1bbf28fce05963e5c9de9f3ef'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Donation: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly foodCategory: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/float8@1']['output'];
      readonly quantityUnit: CodecTypes['pg/text@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly expiryTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly pickupAddress: CodecTypes['pg/text@1']['output'];
      readonly pickupCity: CodecTypes['pg/text@1']['output'];
      readonly pickupDistrict: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'AVAILABLE'
        | 'REQUESTED'
        | 'ACCEPTED'
        | 'PICKED_UP'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELLED';
      readonly providerId: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly DonationRequest: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly donationId: CodecTypes['pg/uuid@1']['output'];
      readonly ngoId: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
      readonly requestedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Pickup: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly donationId: CodecTypes['pg/uuid@1']['output'];
      readonly volunteerId: CodecTypes['pg/uuid@1']['output'];
      readonly requestId: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'PENDING' | 'ASSIGNED' | 'COLLECTED' | 'DELIVERED' | 'CANCELLED';
      readonly qrCode: CodecTypes['pg/text@1']['output'] | null;
      readonly collectedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'RESTAURANT' | 'NGO' | 'VOLUNTEER' | 'ADMIN';
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'PENDING';
      readonly city: CodecTypes['pg/text@1']['output'] | null;
      readonly district: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Donation: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly foodCategory: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/float8@1']['input'];
      readonly quantityUnit: CodecTypes['pg/text@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly expiryTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly pickupAddress: CodecTypes['pg/text@1']['input'];
      readonly pickupCity: CodecTypes['pg/text@1']['input'];
      readonly pickupDistrict: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'AVAILABLE'
        | 'REQUESTED'
        | 'ACCEPTED'
        | 'PICKED_UP'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELLED';
      readonly providerId: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly DonationRequest: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly donationId: CodecTypes['pg/uuid@1']['input'];
      readonly ngoId: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
      readonly requestedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Pickup: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly donationId: CodecTypes['pg/uuid@1']['input'];
      readonly volunteerId: CodecTypes['pg/uuid@1']['input'];
      readonly requestId: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'PENDING' | 'ASSIGNED' | 'COLLECTED' | 'DELIVERED' | 'CANCELLED';
      readonly qrCode: CodecTypes['pg/text@1']['input'] | null;
      readonly collectedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'RESTAURANT' | 'NGO' | 'VOLUNTEER' | 'ADMIN';
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'PENDING';
      readonly city: CodecTypes['pg/text@1']['input'] | null;
      readonly district: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly donation: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly expiryTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly foodCategory: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly pickupAddress: CodecTypes['pg/text@1']['output'];
      readonly pickupCity: CodecTypes['pg/text@1']['output'];
      readonly pickupDistrict: CodecTypes['pg/text@1']['output'];
      readonly providerId: CodecTypes['pg/uuid@1']['output'];
      readonly quantity: CodecTypes['pg/float8@1']['output'];
      readonly quantityUnit: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'AVAILABLE'
        | 'REQUESTED'
        | 'ACCEPTED'
        | 'PICKED_UP'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELLED';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly donationRequest: {
      readonly donationId: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ngoId: CodecTypes['pg/uuid@1']['output'];
      readonly requestedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly pickup: {
      readonly collectedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly donationId: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly qrCode: CodecTypes['pg/text@1']['output'] | null;
      readonly requestId: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'PENDING' | 'ASSIGNED' | 'COLLECTED' | 'DELIVERED' | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly volunteerId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly user: {
      readonly city: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly district: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'RESTAURANT' | 'NGO' | 'VOLUNTEER' | 'ADMIN';
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'PENDING';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly donation: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly expiryTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly foodCategory: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly pickupAddress: CodecTypes['pg/text@1']['input'];
      readonly pickupCity: CodecTypes['pg/text@1']['input'];
      readonly pickupDistrict: CodecTypes['pg/text@1']['input'];
      readonly providerId: CodecTypes['pg/uuid@1']['input'];
      readonly quantity: CodecTypes['pg/float8@1']['input'];
      readonly quantityUnit: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'AVAILABLE'
        | 'REQUESTED'
        | 'ACCEPTED'
        | 'PICKED_UP'
        | 'DELIVERED'
        | 'EXPIRED'
        | 'CANCELLED';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly donationRequest: {
      readonly donationId: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ngoId: CodecTypes['pg/uuid@1']['input'];
      readonly requestedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly pickup: {
      readonly collectedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly donationId: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly qrCode: CodecTypes['pg/text@1']['input'] | null;
      readonly requestId: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'PENDING' | 'ASSIGNED' | 'COLLECTED' | 'DELIVERED' | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly volunteerId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly user: {
      readonly city: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly district: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'RESTAURANT' | 'NGO' | 'VOLUNTEER' | 'ADMIN';
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'PENDING';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/uuid@1']['output'];
    firstName: CodecTypes['pg/text@1']['output'];
    lastName: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    phone: CodecTypes['pg/text@1']['output'] | null;
    role: 'RESTAURANT' | 'NGO' | 'VOLUNTEER' | 'ADMIN';
    status: 'ACTIVE' | 'SUSPENDED' | 'PENDING';
    city: CodecTypes['pg/text@1']['output'] | null;
    district: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    donations: public_Donation[];
    pickups: public_Pickup[];
    requests: public_DonationRequest[];
    readonly [RelationKeys]?: 'donations' | 'pickups' | 'requests';
  };
  export type public_Donation = {
    id: CodecTypes['pg/uuid@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    foodCategory: CodecTypes['pg/text@1']['output'];
    quantity: CodecTypes['pg/float8@1']['output'];
    quantityUnit: CodecTypes['pg/text@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    expiryTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    pickupAddress: CodecTypes['pg/text@1']['output'];
    pickupCity: CodecTypes['pg/text@1']['output'];
    pickupDistrict: CodecTypes['pg/text@1']['output'];
    status:
      'AVAILABLE' | 'REQUESTED' | 'ACCEPTED' | 'PICKED_UP' | 'DELIVERED' | 'EXPIRED' | 'CANCELLED';
    providerId: CodecTypes['pg/uuid@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    pickups: public_Pickup[];
    provider: public_User;
    requests: public_DonationRequest[];
    readonly [RelationKeys]?: 'pickups' | 'provider' | 'requests';
  };
  export type public_DonationRequest = {
    id: CodecTypes['pg/uuid@1']['output'];
    donationId: CodecTypes['pg/uuid@1']['output'];
    ngoId: CodecTypes['pg/uuid@1']['output'];
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
    requestedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    donation: public_Donation;
    ngo: public_User;
    pickup: public_Pickup | null;
    readonly [RelationKeys]?: 'donation' | 'ngo' | 'pickup';
  };
  export type public_Pickup = {
    id: CodecTypes['pg/uuid@1']['output'];
    donationId: CodecTypes['pg/uuid@1']['output'];
    volunteerId: CodecTypes['pg/uuid@1']['output'];
    requestId: CodecTypes['pg/uuid@1']['output'];
    status: 'PENDING' | 'ASSIGNED' | 'COLLECTED' | 'DELIVERED' | 'CANCELLED';
    qrCode: CodecTypes['pg/text@1']['output'] | null;
    collectedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    donation: public_Donation;
    request: public_DonationRequest;
    volunteer: public_User;
    readonly [RelationKeys]?: 'donation' | 'request' | 'volunteer';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Donation: Models.public_Donation;
    DonationRequest: Models.public_DonationRequest;
    Pickup: Models.public_Pickup;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly donation: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly foodCategory: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly quantityUnit: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly expiryTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly pickupAddress: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pickupCity: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pickupDistrict: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AVAILABLE'>;
                  };
                };
                readonly providerId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'donation_providerId_idx_d1904c54';
                  readonly prefix: 'donation_providerId_idx';
                  readonly columns: readonly ['providerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donation';
                    readonly columns: readonly ['providerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly donationRequest: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly donationId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly ngoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly requestedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'donationRequest_donationId_idx_dea7c586';
                  readonly prefix: 'donationRequest_donationId_idx';
                  readonly columns: readonly ['donationId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'donationRequest_ngoId_idx_99c8e6b5';
                  readonly prefix: 'donationRequest_ngoId_idx';
                  readonly columns: readonly ['ngoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donationRequest';
                    readonly columns: readonly ['donationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donation';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donationRequest';
                    readonly columns: readonly ['ngoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pickup: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly donationId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly volunteerId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly requestId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly qrCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly collectedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly deliveredAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['requestId'] },
                { readonly columns: readonly ['qrCode'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'pickup_donationId_idx_dea7c586';
                  readonly prefix: 'pickup_donationId_idx';
                  readonly columns: readonly ['donationId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pickup_volunteerId_idx_b41cb3e4';
                  readonly prefix: 'pickup_volunteerId_idx';
                  readonly columns: readonly ['volunteerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pickup';
                    readonly columns: readonly ['donationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donation';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pickup';
                    readonly columns: readonly ['volunteerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pickup';
                    readonly columns: readonly ['requestId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'donationRequest';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly district: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly DonationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'AVAILABLE',
                'REQUESTED',
                'ACCEPTED',
                'PICKED_UP',
                'DELIVERED',
                'EXPIRED',
                'CANCELLED',
              ];
            };
            readonly PickupStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'ASSIGNED',
                'COLLECTED',
                'DELIVERED',
                'CANCELLED',
              ];
            };
            readonly RequestStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'COMPLETED',
              ];
            };
            readonly UserRole: {
              readonly kind: 'valueSet';
              readonly values: readonly ['RESTAURANT', 'NGO', 'VOLUNTEER', 'ADMIN'];
            };
            readonly UserStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'SUSPENDED', 'PENDING'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly donation: { readonly namespace: 'public' & NamespaceId; readonly model: 'Donation' };
    readonly donationRequest: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DonationRequest';
    };
    readonly pickup: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pickup' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Donation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly foodCategory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly quantityUnit: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiryTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly pickupAddress: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pickupCity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pickupDistrict: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly providerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly pickups: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pickup';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['donationId'];
                };
              };
              readonly provider: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['providerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly requests: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DonationRequest';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['donationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'donation';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly description: { readonly column: 'description' };
                readonly foodCategory: { readonly column: 'foodCategory' };
                readonly quantity: { readonly column: 'quantity' };
                readonly quantityUnit: { readonly column: 'quantityUnit' };
                readonly imageUrl: { readonly column: 'imageUrl' };
                readonly expiryTime: { readonly column: 'expiryTime' };
                readonly pickupAddress: { readonly column: 'pickupAddress' };
                readonly pickupCity: { readonly column: 'pickupCity' };
                readonly pickupDistrict: { readonly column: 'pickupDistrict' };
                readonly status: { readonly column: 'status' };
                readonly providerId: { readonly column: 'providerId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly DonationRequest: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly donationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ngoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly requestedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly donation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Donation';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['donationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly ngo: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['ngoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly pickup: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pickup';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['requestId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'donationRequest';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly donationId: { readonly column: 'donationId' };
                readonly ngoId: { readonly column: 'ngoId' };
                readonly status: { readonly column: 'status' };
                readonly requestedAt: { readonly column: 'requestedAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Pickup: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly donationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly volunteerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly requestId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly qrCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly collectedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly deliveredAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly donation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Donation';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['donationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly request: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DonationRequest';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['requestId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly volunteer: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['volunteerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pickup';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly donationId: { readonly column: 'donationId' };
                readonly volunteerId: { readonly column: 'volunteerId' };
                readonly requestId: { readonly column: 'requestId' };
                readonly status: { readonly column: 'status' };
                readonly qrCode: { readonly column: 'qrCode' };
                readonly collectedAt: { readonly column: 'collectedAt' };
                readonly deliveredAt: { readonly column: 'deliveredAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly district: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly donations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Donation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['providerId'];
                };
              };
              readonly pickups: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pickup';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['volunteerId'];
                };
              };
              readonly requests: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DonationRequest';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['ngoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly firstName: { readonly column: 'firstName' };
                readonly lastName: { readonly column: 'lastName' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly phone: { readonly column: 'phone' };
                readonly role: { readonly column: 'role' };
                readonly status: { readonly column: 'status' };
                readonly city: { readonly column: 'city' };
                readonly district: { readonly column: 'district' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly UserRole: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'RESTAURANT'; readonly value: 'RESTAURANT' },
              { readonly name: 'NGO'; readonly value: 'NGO' },
              { readonly name: 'VOLUNTEER'; readonly value: 'VOLUNTEER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
            ];
          };
          readonly UserStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'SUSPENDED'; readonly value: 'SUSPENDED' },
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
            ];
          };
          readonly DonationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AVAILABLE'; readonly value: 'AVAILABLE' },
              { readonly name: 'REQUESTED'; readonly value: 'REQUESTED' },
              { readonly name: 'ACCEPTED'; readonly value: 'ACCEPTED' },
              { readonly name: 'PICKED_UP'; readonly value: 'PICKED_UP' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'EXPIRED'; readonly value: 'EXPIRED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly RequestStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'APPROVED'; readonly value: 'APPROVED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
            ];
          };
          readonly PickupStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'ASSIGNED'; readonly value: 'ASSIGNED' },
              { readonly name: 'COLLECTED'; readonly value: 'COLLECTED' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'donation';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'donation';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'donationRequest';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'donationRequest';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pickup';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pickup';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
